### PR TITLE
Features/cleanup status

### PR DESCRIPTION
**Pull request by andresgongora**
- Fix bug when some commands are not found with which
- Improve getIP*, shorter regex
- Move all status code into own print* functions
- Add extra helper functions with common formatting to unify overall behavior
- Prepare main function for separate logo and text printing
- Wrap the script in a single function to avoid environment pollution
- Extra comments on codingstyle
- Other minor fixes

### CODE REVIEW

**Comment by andresgongora** [comment]
@olmari Please take a look at status.sh, it has changed A LOT. Please tell me if the new changes mean conflicts for you to try solving them.

Overall, status.sh is now much sleeker (the file is bigger, but the code footprint is much smaller with lot's of reuse). Also, it's now SO MUCH MORE intuitive to work with. Except getIP6 (pending #46 ) everything else is now in a more logical place and has more descriptive names to aid in the big change that is to come with #52 .

**Comment by olmari** [comment]
I will in some hours, away at the moment :)

**Comment by olmari** [comment]
Generally I like the improvements a lot!

Few notes tough:

## "Improve getIP*, shorter regex"

regex for both IP-versions, but especially IPv6 was long because it matched exactly _valid_ IPv6 numbers, including the exotic transit numbers which has ipv4-style addres thrown in to the actual IPv6 address... While it IS messy looking regex, it validates real IP-numbers, not just "looking like one".. Also the long regex isn't that demanding on CPU, earlier rules in the "my" validation made sure we don't even reach that validation regex until we hit in "inet{6} addr" line...

If it makes code more readable, we can allways put regex into variable and use that in code then... 

Now I don't  know how important it is to validate IP-numbers in reality, but I like to be pedantic :)

## Actual bug:

I still see the "printf Y" error happening on the startup

**Comment by andresgongora** [comment]
Ok. I'll revert the ipv6 back to the original. I didn't know all that.

About the bug... That's weird... I'll take a look at it and try something
new. But doing you see a valid date?

**Comment by olmari** [comment]
No date shown on status.

If I take out quotes from config, I do get date showing, but still see the error on startup.

**Comment by olmari** [comment]
Other than those, I do like the overall lookings of status.sh, way more easy to read, also I like sed/grep groupings done in functions (that has some of those). Feels great improvement!

**Comment by olmari** [comment]
Now the actual bugs (actually 2 related ones) are fixed.

**Pull request merged**
