### PR TITLE
Features/git-info

### PR DESCRIPTION
**Pull request by andresgongora**
- [x] Extract `getAbridgedPWD` and address #57 
- [ ] Implement requests from #97 
- [ ] Add a new function that updates the `git branch name` depending on the current directory, to omit the 4th triangle/separator when not needed.
- [x] Make function more modular such that extra segments can be added in the future in an easier way. Might also solve the above problem of updating `git-branch-name`.

### CODE REVIEW

**Comment by andresgongora** [comment]
Well, it's WAY more ddificult that initially suspected. The main problem is that any function called using the hook `PROMPT_COMMAND` does not have access to the configuration variables. This implies that the format has to be applied to PS1 externally, which in turn means that the color of the triangles can NOT be changed depending of whether inside a git repository or not... unless the configuration is stored in global variables; which I think is a bad idea.

**Comment by olmari** [comment]
I'd say that changing of color is not directly the issue... why would be change colors? I'd say better to not show "4th" bar and connected "arrow" at all when not in git repo, ought to be possible? :)

**Comment by andresgongora** [comment]
You need access to some sort of memory for that. Once in that function, you
don't know what the 4th triangle is. And you can't generate it (the
decoration, that is) without the colors.

**Comment by andresgongora** [comment]
I managed to clean everything up. I still want to make all elements optional, which I think I can do by assembling the `PS1` string recursively, starting from the `USER INPUT` format, and working my way back to `USER`.

However, I'm still unable to pass format information to `PROMPT_COMMAND`.

**Comment by fikoborizqy** [comment]
I'm so sorry I wasn't on my laptop since I created that pull request.
I created update on your requests:
- doc/screenshot.png: Please don't change it for now.
- terminal/fancy-bash-prompt.sh: change indents from spaces to tabs.
- condition fourth separator on the presence of a repository. If pwd is not inside of a repository, leave it empty such that it does not display the "triangle" character.

image

**Comment by andresgongora** [comment]
@fikoborizqy Has had an idea in which two PS1 prompts are exported, and the one that is shown depends on whether the repository is a git folder or not (see #101 ).

I like this idea. It still means that we are exporting information into the global environment... but this has be ignored for the sake of a beautiful prompt. I will merge #101 (and fix the conflicts) later today, and take the suggestion one step further to select specific elements for the prompt.

**Comment by andresgongora** [comment]
Commit 2266522 implements the changes from #101, but merges them with the new format. It hink you will like it, @fikoborizqy.

Still working on making everything optional (i.e. user configurable).

**Comment by andresgongora** [comment]
@fikoborizqy From your screenshot I see dome "noise" around the triangles that make up the prompt. If you want to fix that, consider installing the font HACK. Depending on the nix distribution you are using, it is sually called either `ttf-hack` or `hack-ttf`. After you isntall it, you only have to tell your terminal yo use it. Notice the difference:

image


image

**Comment by andresgongora** [comment]
Merging now. It's still not perfect. But it works.
Showing the git branch is now optional (in configuration file) and OFF by default.

**Comment by fikoborizqy** [comment]
> @fikoborizqy From your screenshot I see dome "noise" around the triangles that make up the prompt. If you want to fix that, consider installing the font HACK. Depending on the nix distribution you are using, it is sually called either `ttf-hack` or `hack-ttf`. After you isntall it, you only have to tell your terminal yo use it. Notice the difference:
> 
> image
> 
> image

Thank you for your suggestion, it's awecome, I love it ;)
image

**Pull request merged**
