### PR TITLE
Show Current Branch Name

### PR DESCRIPTION
**Pull request by fikoborizqy**
Automatically show current branch name on terminal without always typing "git branch".

image

### CODE REVIEW

**Comment by olmari** [comment]
Looks interesting to me! Need to look better when at computer.

One thing I would like to see improved from looking the screenshot: if possible, show no purple arrow at all when not in git branched place (but tjese we can always improve later too).

**Comment by andresgongora** [comment]
I like your idea, but it should only appear if inside a folder that's actually a repo (maybe check for a `.git` folder, or the error output og `git status`?). If you could fix that, your addition would be awesome!!

Honestly, I like the idea!

**Comment by andresgongora** [comment]
Changed pull request from `master` to `develop`.

@fikoborizqy please fix following conflicts and I'll immediately merge your request! :D
- [ ] doc/screenshot.png: Please don't change it for now.
- [ ] terminal/fancy-bash-prompt.sh: change indents from spaces to tabs.
- [ ] condition fourth separator on the presence of a repository. If pwd is not inside of a repository, leave it empty such that it does not display the "triangle" character.

**Comment by andresgongora** [comment]
Added #97

**Comment by andresgongora** [comment]
I moved the pull request to its own branch to follow our work-flow. That way we can expand tinker on this idea until its ready to be merged in :D

**Pull request merged**
